### ISSUE TITLE
FileMonitor SNTL file not loading Properly

### ISSUE THREAD

**Issue by 240026763** [yarseyah/sentinel#11]
I have an nlog generated log file that I would like to view in Sentinel.  When I load sentinel and go through the wizard, the provider works as expected. However, when I save the sntl file and reload sentinel with it, the information is blank and doesn't update with new entries.

**Comment by yarseyah** [comment]
Do you have an example SNTL file?  Redact filenames if necessary.

**Comment by 240026763** [comment]
Here is the sntl file and a sample log file that it "should" pull up.  I have tried both trying to load the sntl as an argument to application and by using the load command.
[Sentinel-UnifiedTester.zip](https://github.com/yarseyah/sentinel/files/3811274/Sentinel-UnifiedTester.zip)

**Comment by 240026763** [comment]
Any thoughts on this?  I haven't been able to locate the problem.  When debugging, it appears to pull in the sntl file just fine and the FileMonitor object is found.  There just seems to be a disconnect from that point further.

**Comment by 240026763** [comment]
Both loading an sntl file as a command arg or choosing to open the sntl file just bring up an empty log window.

**Comment by yarseyah** [comment]
Very overdue, but I managed to take a look and it seems that the code to reinflate providers did not factor in the FileMonitorProvider.  Added that as a case and it now looks to work as expected.

Will post 0.14.1 as a fix for this.
