### ISSUE TITLE
Clear window

### ISSUE THREAD

**Issue by tinmac** [yarseyah/sentinel#15]
Amazing app, been struggling with others and found sentinel! Pleased isn't in it! 

Question: I would like to clear the log viewer main window by sending a magic string eg nlogr.Trace("clear the sentinel screen please") 

Or do you have any other way of accomplishing this lazy mans functionality??

Cheers

**Comment by yarseyah** [comment]
I've implemented something basic within the 0.13.6.0 release I just pushed.  Define the string you want to look for in the Preferences Commands tab.

Current version doesn't save settings between sessions correctly, but since the default of `#!Clear` is likely to be rare I thought better to share.
