### ISSUE TITLE
Squirrel upgrader error

### ISSUE THREAD

**Issue by dalebrubaker** [yarseyah/sentinel#20]
Using the latest release, a big red banner at the top: "Squirrel upgrader has the following errrors
Updater.exe is not found, not a Squirrel-installed app?"

I'm using NLog provider from a WinForms desktop app, .net framework

**Comment by yarseyah** [comment]
Did you use the installer or are you running from sources you have built?

**Comment by yarseyah** [comment]
If your are intending to run locally built code, you can either generate the installer using the `New-Installer.ps1` powershell script or pass `--inhibit-upgrade` in on the command line to prevent checks at all.

**Comment by dalebrubaker** [comment]
I was using source I built from source. Thanks for the tip about the
installer.
