### ISSUE TITLE
View From Remote Machine

### ISSUE THREAD

**Issue by AlexVPerl** [yarseyah/sentinel#9]
Is it possible to view logs from a remote machine by IP?

**Comment by yarseyah** [comment]
The original point of Sentinal was to be the remote observer, whilst it could be possible to have a client/server link from the logger service  to the front end, you could just as easily instruct the logger to send to the the machine showing the logs?

**Comment by AlexVPerl** [comment]
Thanks for mentioning that. I'm using nLog and I know it has a verity of targets available. Do you have any examples / links you could share?

**Comment by yarseyah** [comment]
There is an example on the main readme, https://github.com/yarseyah/sentinel/blob/master/README.md#nlogs-nlogviewer-target-configuration
